name: deploy
on:
  push:
    branches: ['main']
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: make application.properties
        if: contains(github.ref, 'main')
        run: |
          cd ./src/main/resources
          touch ./application-conf.properties
          echo "${{ secrets.SECRET_PROPERTIES }}" > ./application-conf.properties
          echo "${{ secrets.SECRET_PROPERTIES }}" > ./application-deploy.properties
        shell: bash

        ## gradle build
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --exclude-task test

      ## docker build & push to main
      - name: Docker build & push
        if: contains(github.ref, 'main')
        run: |
          docker build -t artique-admin -f Dockerfile .
          docker save artique-admin > artique-admin-container.tar
      - name: SCP Docker file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./artique-admin-container.tar"
          target: "/home/ubuntu/artique/admin"

      ## deploy to main
      - name: Deploy to main server
        uses: appleboy/ssh-action@master
        id: deploy-main
        if: contains(github.ref, 'main')
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/artique/admin
            sudo sh deploy.sh